// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const SwitchEvent = __t.object("SwitchEvent", {
  deviceId: __t.string(),
  ipHash: __t.string(),
  distroKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type SwitchEvent = __Infer<typeof SwitchEvent>;

