import type { SoftwareItem } from "./types";

export const SOFTWARE_CATALOG: SoftwareItem[] = [
  {
    id: "steam",
    label: "Steam / most Steam games",
    category: "Games",
    linuxStatus: "native",
    note: "Native client; Proton covers many Windows-only titles.",
  },
  {
    id: "lol",
    label: "League of Legends",
    category: "Games",
    linuxStatus: "no_practical_alternative",
    note: "Anti-cheat policy has historically blocked Linux; check current Riot stance.",
  },
  {
    id: "valorant",
    label: "Valorant",
    category: "Games",
    linuxStatus: "no_practical_alternative",
    note: "Vanguard anti-cheat does not support Linux.",
  },
  {
    id: "fortnite",
    label: "Fortnite",
    category: "Games",
    linuxStatus: "no_practical_alternative",
    note: "Easy Anti-Cheat configuration for Linux has been restrictive.",
  },
  {
    id: "minecraft",
    label: "Minecraft (Java)",
    category: "Games",
    linuxStatus: "native",
  },
  {
    id: "wow",
    label: "World of Warcraft",
    category: "Games",
    linuxStatus: "workable",
    note: "Often via Wine/Proton; Blizzard launcher can be fiddly.",
  },
  {
    id: "adobe_cc",
    label: "Adobe Creative Cloud (Photoshop, Premiere, After Effects)",
    category: "Creative",
    linuxStatus: "no_practical_alternative",
    note: "No supported native suite; alternatives like DaVinci, Krita, GIMP differ in workflow.",
  },
  {
    id: "davinci",
    label: "DaVinci Resolve",
    category: "Creative",
    linuxStatus: "native",
  },
  {
    id: "blender",
    label: "Blender",
    category: "Creative",
    linuxStatus: "native",
  },
  {
    id: "figma",
    label: "Figma (desktop)",
    category: "Creative",
    linuxStatus: "cloud_only",
    note: "Use the browser; no official native Linux desktop parity.",
  },
  {
    id: "ms_office",
    label: "Microsoft Office (native Windows)",
    category: "Productivity",
    linuxStatus: "workable",
    note: "LibreOffice / OnlyOffice; or Office web. Macros and complex Excel may differ.",
  },
  {
    id: "outlook",
    label: "Outlook desktop (classic)",
    category: "Productivity",
    linuxStatus: "workable",
    note: "Web Outlook or Thunderbird / Evolution.",
  },
  {
    id: "teams",
    label: "Microsoft Teams",
    category: "Productivity",
    linuxStatus: "native",
    note: "Official Linux builds exist; quality varies by org policy.",
  },
  {
    id: "slack",
    label: "Slack",
    category: "Productivity",
    linuxStatus: "native",
  },
  {
    id: "discord",
    label: "Discord",
    category: "Productivity",
    linuxStatus: "native",
  },
  {
    id: "zoom",
    label: "Zoom",
    category: "Productivity",
    linuxStatus: "native",
  },
  {
    id: "solidworks",
    label: "SolidWorks",
    category: "CAD / 3D",
    linuxStatus: "no_practical_alternative",
    note: "No supported Linux release; dual-boot or VM often used.",
  },
  {
    id: "fusion360",
    label: "Autodesk Fusion 360",
    category: "CAD / 3D",
    linuxStatus: "workable",
    note: "Community scripts / wine approaches; not officially supported on Linux.",
  },
  {
    id: "autocad",
    label: "AutoCAD",
    category: "CAD / 3D",
    linuxStatus: "no_practical_alternative",
    note: "No native Linux; alternatives like FreeCAD differ substantially.",
  },
  {
    id: "freecad",
    label: "FreeCAD",
    category: "CAD / 3D",
    linuxStatus: "native",
  },
  {
    id: "ableton",
    label: "Ableton Live",
    category: "Audio",
    linuxStatus: "no_practical_alternative",
    note: "No native Linux; Bitwig / REAPER are common alternatives.",
  },
  {
    id: "bitwig",
    label: "Bitwig Studio",
    category: "Audio",
    linuxStatus: "native",
  },
  {
    id: "reaper",
    label: "REAPER",
    category: "Audio",
    linuxStatus: "native",
  },
  {
    id: "fl_studio",
    label: "FL Studio",
    category: "Audio",
    linuxStatus: "native",
    note: "Native Linux build available (verify edition/features you need).",
  },
  {
    id: "vscode",
    label: "Visual Studio Code",
    category: "Development",
    linuxStatus: "native",
  },
  {
    id: "vstudio",
    label: "Visual Studio (IDE, not Code)",
    category: "Development",
    linuxStatus: "no_practical_alternative",
    note: "Windows/macOS only; use VS Code, Rider, or JetBrains on Linux.",
  },
  {
    id: "docker_desktop",
    label: "Docker Desktop",
    category: "Development",
    linuxStatus: "native",
  },
  {
    id: "wsl_workflow",
    label: "A workflow built heavily around WSL + Windows tooling",
    category: "Development",
    linuxStatus: "workable",
    note: "On Linux you use native containers and native paths; migration effort varies.",
  },
  {
    id: "nvidia_broadcast",
    label: "NVIDIA Broadcast / RTX Voice (Windows-only features)",
    category: "Streaming",
    linuxStatus: "workable",
    note: "PipeWire + noise plugins differ; not identical.",
  },
  {
    id: "obs",
    label: "OBS Studio",
    category: "Streaming",
    linuxStatus: "native",
  },
  {
    id: "chrome",
    label: "Google Chrome",
    category: "Web",
    linuxStatus: "native",
  },
  {
    id: "edge",
    label: "Microsoft Edge",
    category: "Web",
    linuxStatus: "native",
  },
  {
    id: "one_drive",
    label: "OneDrive sync (official client experience)",
    category: "Cloud",
    linuxStatus: "workable",
    note: "Community clients or Insync; not identical to Windows shell integration.",
  },
  {
    id: "icloud",
    label: "iCloud for Windows-style workflow",
    category: "Cloud",
    linuxStatus: "workable",
    note: "Web and selective tooling; seamless iCloud desktop sync is limited.",
  },
];

export function getSoftwareById(id: string): SoftwareItem | undefined {
  return SOFTWARE_CATALOG.find((s) => s.id === id);
}
